### PR TITLE
Don't cast Asana workspace ID to int

### PR DESCRIPTION
**Pull request by sgrimm-sg**
Asana's API expects workspace IDs to be passed as strings, not numbers, and it has recently started enforcing that expectation. This causes task creation from the Sentry UI to fail with an error, "Error Communicating with Asana (HTTP 400): workspace: Not a valid GID type: number".

### CODE REVIEW

**Comment by sgrimm-sg** [comment]
What does the schedule look like for rolling this kind of change out to sentry.io?

**Comment by markstory** [comment]
@sgrimm-sg It should have gone out 5 days ago.

**Comment by okdewit** [comment]
@markstory I can confirm it's not online on the paid hosted service yet:

image

**Comment by okdewit** [comment]
@markstory I'm not very familiar with Python 2.x development, but I made a PR which might resolve the remaining issue:
https://github.com/getsentry/sentry-plugins/pull/508
The build is currently failing, although it doesn't seem to fail on the changes in the PR.

**Pull request merged**
