### PR TITLE
feat(vsts): Add repository provider

### PR DESCRIPTION
**Pull request by dcramer**
Requires getsentry/sentry#6135

### CODE REVIEW

**Comment by dcramer** [comment]
This includes some more minor refactoring of the bitbucket plugin

**Comment by dcramer** [comment]
I can explore getting some basic tests in, but I did full QA passes on this.

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dcramer** [comment]
Added coverage for repos UI

**Comment by MaxBittker** [comment]
did you see the test failures here?

**Comment by dcramer** [comment]
failures are unrelated so going to ship this

**Pull request merged**
