### PR TITLE
feat(vsts): Add Visual Studio extension

### PR DESCRIPTION
**Pull request by dcramer**
Add basic VSTS integration using refactored components from JIRA, GitHub, and Asana. Also update LICENSES to be more correct. Currently it is limited to the 'Create Issue' action.

Fixes getsentry/sentry#5263

See also https://github.com/boylec/sentry-vsts/issues/5

### CODE REVIEW

**Comment by dcramer** [comment]
Actually I'm going to implement OAuth before we do this

https://www.visualstudio.com/en-us/docs/integrate/get-started/authentication/oauth

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Do not modify the License</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Changes to build requirements</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/pull/6124

**Comment by dcramer** [comment]
Would be great to follow up and add a basic repository provider. May not have webhooks, but we can always on-demand scrape commits when a release is created.

https://www.visualstudio.com/en-us/docs/integrate/api/git/overview

**Comment by dcramer** [comment]
Still some more cleanup, but in a good spot now.

- Uses OAuth for credentials (via linked changeset)
- Uses standard utilities for API calls and response handling

In the future we should:

- Add select of account/project to the create issue form
- Add 'Link Issue' action

**Comment by dcramer** [comment]
I also standardized a bunch of the redundant API client code, and we could probably re-use it for most if not all of the integrations to greatly trim down on semi-broken behavior.

**Comment by dcramer** [comment]
making a few more changes to future proof this

**Comment by dcramer** [comment]
- Removed fixed project
- Added link issue
- Future proofed things for on-premise installs, changing instance, etc

http://i.cra.mr/2V2X3L2t0I1E

**Comment by dcramer** [comment]
@macqueen ok rebased this though I will also do a review of the github changes now just in case i messed up something during the merge

**Pull request merged**
