### PR TITLE
fix(pagerduty) Fix failing incident creation

### PR DESCRIPTION
**Pull request by markstory**
Pagerduty recently started enforcing strict parameter types and has been
rejecting our requests for a few days now.

Fixes SEN-606

### CODE REVIEW

**Comment by NicoleYson** [comment]
Do you know when this will be released?  
It looks like the last release was 25 days ago and this is an issue for us ☝️

**Comment by markstory** [comment]
@NicoleYson You can install `master` until a tag is created. Right now this repository has lockstep releases with the main sentry repository so it might be a while before another release is created.

**Comment by changohk** [comment]
Is there anyone know the release date if it has been planned?
we are still under this issue.
we are looking for how to move forward to solve this issue without other impacts.
if anyone made a success please share with me the best practice.

**Comment by markstory** [comment]
@changohk You can use `pip install` to update `sentry-plugins` from git master.

**Comment by changohk** [comment]
@markstory 
It seems we updated successfully from git master as in below picture.
However, we are still under problem. PD cannot receive events from Sentry plugin. 
I am wondering anyone solved this issue by installing from git master?

스크린샷 2019-06-04 오후 4 39 13

**Comment by markstory** [comment]
What is the error you are getting from pagerduty?

**Comment by vinhlh** [comment]
```
warning: no files found matching 'src/sentry_plugins/assets.json'
    warning: no files found matching '*.js' under directory 'src/sentry_plugins'
    warning: no files found matching '*.css' under directory 'src/sentry_plugins'
    warning: no files found matching '*.js.gz' under directory 'src/sentry_plugins'
    warning: no files found matching '*.js.map' under directory 'src/sentry_plugins'
    warning: no previously-included files matching '*~' found anywhere in distribution
    writing manifest file 'src/sentry_plugins.egg-info/SOURCES.txt'
    creating build/lib/sentry_plugins/sessionstack/static
    creating build/lib/sentry_plugins/sessionstack/static/sessionstack
    copying src/sentry_plugins/sessionstack/static/sessionstack/sessionstack.jsx -> build/lib/sentry_plugins/sessionstack/static/sessionstack
    creating build/lib/sentry_plugins/sessionstack/static/sessionstack/components
    copying src/sentry_plugins/sessionstack/static/sessionstack/components/settings.jsx -> build/lib/sentry_plugins/sessionstack/static/sessionstack/components
    creating build/lib/sentry_plugins/sessionstack/static/sessionstack/contexts
    copying src/sentry_plugins/sessionstack/static/sessionstack/contexts/sessionstack.jsx -> build/lib/sentry_plugins/sessionstack/static/sessionstack/contexts
    creating build/lib/sentry_plugins/jira/static
    creating build/lib/sentry_plugins/jira/static/jira
    copying src/sentry_plugins/jira/static/jira/jira.jsx -> build/lib/sentry_plugins/jira/static/jira
    creating build/lib/sentry_plugins/jira/static/jira/components
    copying src/sentry_plugins/jira/static/jira/components/issueActions.jsx -> build/lib/sentry_plugins/jira/static/jira/components
    copying src/sentry_plugins/jira/static/jira/components/settings.jsx -> build/lib/sentry_plugins/jira/static/jira/components
    creating build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/base.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/config.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/error.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/signin.html -> build/lib/sentry_plugins/jira_ac/templates
    copying src/sentry_plugins/jira_ac/templates/widget.html -> build/lib/sentry_plugins/jira_ac/templates
    running build_assets
    command failed [node --version] via [/tmp/pip-req-build-Kssaf8]
    Cannot find `node` executable. Please install node` and try again.
```

I have this error when trying to install latest version.

**Comment by mattrobenolt** [comment]
Your error literally tells you exactly what the problem is. You need node.

**Comment by vinhlh** [comment]
For those have this issue, beside installing NodeJS, we need to set `SENTRY_BUILD` to fix `Could not determine sentry version or build` error.

```Dockerfile
# To fix pagerduty issue described in https://github.com/getsentry/sentry-plugins/pull/469
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get -y install nodejs
ENV SENTRY_BUILD 9
RUN pip install https://github.com/getsentry/sentry-plugins/archive/3dbfd39c8931a39563dfe2a964c3aeda2573bd99.zip
```

**Comment by mattrobenolt** [comment]
I would not recommend doing what is posted above. That is 1, installing two different versions of node, and a version of node we don't support.

If you're trying to do something in docker, you should at least follow what we do as best practice: https://github.com/getsentry/docker-sentry/blob/master/git/Dockerfile#L88-L142

**Comment by vinhlh** [comment]
Thanks @mattrobenolt, really good to know 👍

**Comment by vinhlh** [comment]
image
Hmm, another error appeared, do you guys have any idea?

**Comment by mattrobenolt** [comment]
Can you post a full stack trace? And what version of sentry are you running this with?

**Comment by vinhlh** [comment]
```
TypeError: get_absolute_url() got an unexpected keyword argument 'params'
  File "sentry/api/endpoints/project_plugin_details.py", line 56, in post
    test_results = plugin.test_configuration(project)
  File "sentry/plugins/bases/notify.py", line 167, in test_configuration
    return self.notify(notification)
  File "sentry/plugins/bases/notify.py", line 69, in notify
    return self.notify_users(event.group, event)
  File "sentry_plugins/pagerduty/plugin.py", line 63, in notify_users
    'url': group.get_absolute_url(params={'referrer': 'pagerduty_plugin'}),
  File "django/utils/functional.py", line 15, in _curried
    return _curried_func(*(args + moreargs), **dict(kwargs, **morekwargs))
  File "django/db/models/base.py", line 1009, in get_absolute_url
    return settings.ABSOLUTE_URL_OVERRIDES.get('%s.%s' % (opts.app_label, opts.model_name), func)(self, *args, **kwargs)
```
I'm using 9.0.0, would it be the cause?

**Comment by mattrobenolt** [comment]
Most likely. At least try against 9.1.1.

**Comment by vinhlh** [comment]
You're right, https://github.com/getsentry/sentry/blob/9.0.0/src/sentry/models/group.py#L246, 9.1 changed the API.

**Pull request merged**
