### PR TITLE
[redmine] Add Redmine plugin

### PR DESCRIPTION
**Pull request by tonyo**
Hi,

I've taken the liberty to port the Redmine plugin (currently located at https://github.com/getsentry/sentry-redmine) to the new architecture because we at our company use it extensively with an older version of Sentry. 
No autocompletion or fancy React components so far, but I'd be interested in looking into those.

Comments & feedback are appreciated, of course.

### CODE REVIEW

**Comment by rev112** [comment]
Looks like the`bundle exec danger` step is failing on Travis. Could someone clarify what went wrong?

**Comment by mattrobenolt** [comment]
> Looks like thebundle exec danger step is failing on Travis. Could someone clarify what went wrong?

We haven't fixed this yet. But it will fail 100% of the time for outside contributors. So don't worry about that.

**Comment by rev112** [comment]
Hi, is there any chance of having this PR checked before any other significant API changes?

**Comment by hugoseabra** [comment]
Is this plugin to be fixed? @mattrobenolt @tonyo ?

**Comment by alexanderadam** [comment]
I suspect that the time of a simple merge is over?
Is there any particular reason why this PR got stale or was it just because of organizational issues?

Is there a chance for a second try, because this is obviously a useful integration.

**Pull request closed without merging**
