### PR TITLE
add jira atlassian connect plugin

### PR DESCRIPTION
**Pull request by macqueen**
still working on a few ui things, but this is pretty much done

screenshot 2016-09-07 18 02 30

@getsentry/plugins @getsentry/ui

---
This change is [Reviewable](https://reviewable.io/reviews/getsentry/sentry-plugins/13)

### CODE REVIEW

**Comment by cameronmcefee** [comment]
😍  I stand corrected, I guess there was room for visual improvement

**Comment by dcramer** [comment]
Could we do "19 minutes ago - 12 hours old" for the subtext? Then we get both last seen and age.

**Comment by macqueen** [comment]
@cameronmcefee the visual improvements were all @ckj's idea, but agree, muuuch better than it was

**Comment by macqueen** [comment]
ok, updated the subtext (and also added some info/warning level issues to show those colors):
screenshot 2016-09-08 13 27 13
and empty state:
screenshot 2016-09-08 15 42 30

the configuration page:
screenshot 2016-09-08 15 16 48

the login page (which looks kinda silly in the large version... suggestions welcome):
screenshot 2016-09-08 15 17 05
screenshot 2016-09-08 14 14 45

**Comment by benvinegar** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/sentry_plugins/jira_ac/templates/signin.html, line 25 at r4](https://reviewable.io:443/reviews/getsentry/sentry-plugins/13#-KR_PSTRD4GUtEWHea8S:-KR_PSTSEgUe8IkuJwaz:bz83m38) ([raw file](https://github.com/getsentry/sentry-plugins/blob/b373ff111c7c16e1cb1ec3a4b168065b0fefd602/src/sentry_plugins/jira_ac/templates/signin.html#L25)):*
> ```HTML
> {% block javascript %}
>   <script type="text/javascript">
>     var hidden, visibilityChange;
> ```

Move the IIFE from below earlier to wrap these `var` declarations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-plugins/13)*

**Comment by benvinegar** [comment]
Reviewed 1 of 9 files at r3, 3 of 5 files at r4, 1 of 1 files at r5.
Review status: 5 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-plugins/13)*

**Comment by dcramer** [comment]
Reviewed 4 of 15 files at r1, 1 of 1 files at r2, 6 of 9 files at r3, 4 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/getsentry/sentry-plugins/13)*

**Comment by benvinegar** [comment]
‼️

**Pull request merged**
