### PR TITLE
fix: Disallow redirects by default on non-GET API calls

### PR DESCRIPTION
**Pull request by dcramer**
With vsts we were hitting a 302, which was causing excess confusion on what the (still invalid) response was.

### CODE REVIEW

**Comment by dcramer** [comment]
@macqueen @MaxBittker are you aware of any integrations that were relying on redirects?

**Comment by dcramer** [comment]
Refs getsentry/sentry#6184

**Comment by macqueen** [comment]
@dcramer yeah i think github did

**Comment by macqueen** [comment]
https://github.com/getsentry/sentry-plugins/pull/67

**Comment by dcramer** [comment]
Ok I'll enable for GitHub, and we can reactively enable case-by-case after that.

**Comment by dcramer** [comment]
Improved behavior to only enable redirects on GET by default, and to enable fully on GitHub

**Comment by mattrobenolt** [comment]
> Improved behavior to only enable redirects on GET by default, and to enable fully on GitHub

To be fair, most things shouldn't follow redirects on say, POST. Actually surprised if this is the behavior internally. :/

**Comment by dcramer** [comment]
@mattrobenolt it was PATCH, so could always be a flaw in requests

**Pull request merged**
