### PR TITLE
[sessionstack] Enable SessionStack plugin for all platforms

### PR DESCRIPTION
**Pull request by lsnickolov**

### CODE REVIEW

**Comment by mattrobenolt** [comment]
I need to look at this very closely. I think this has a major ramification.

**Comment by mattrobenolt** [comment]
Ok, this should be fine. (We need to get our test suite fixed here though)

**Comment by lsnickolov** [comment]
@mattrobenolt, is there something that we need to do to get it fixed?

**Comment by mattrobenolt** [comment]
Nope. @MaxBittker just pointed this out to me yesterday. So we’ll get master fixed up and probably go ahead and get this merged today after this is cleared up. Sorry about that. :(

**Comment by mattrobenolt** [comment]
@lsnickolov Do you mind rebasing off latest master? Looks like things are fixed up in https://github.com/getsentry/sentry-plugins/commit/f39c3331cc92434acdaec9283b2fa693c0b445a5

**Pull request merged**
