### PR TITLE
ref: Clean up client error handling across plugins

### PR DESCRIPTION
**Pull request by dcramer**
- Move GitHub to api client abstractions
- Move Bitbucket to api client abstractions
- Clean up various duplicated code
- Add basic unit tests for ApiClient and AuthApiClient

### CODE REVIEW

**Comment by getsentry-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You should update CHANGES due to the size of this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by dcramer** [comment]
I will ship this tomorrow given its a larger change and not all of this has automated tests.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/pull/6244

**Comment by dcramer** [comment]
🚢  and 🙏

**Pull request merged**
