### PR TITLE
Added ability to slack plugin to send events to different channels depending on the value of a tag.

### PR DESCRIPTION
**Pull request by Eredian**
Adapted from https://github.com/getsentry/sentry-slack/pull/43.

This is something we required to send events coming from different portions of the same application to the right team in slack.

Provides configuration so that a specific tag can be used to direct the events to the right channel depending on that tag's value.

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Why didn't you go through an remove all the trailing commas? Can you please put those back. They are much preferred in Python and have the potential to cause inintended bugs.

**Comment by Eredian** [comment]
I put back the commas, if I'm not mistaken the travis issue is not caused by this PR? Looks like a missing environment variable for danger.

**Comment by mattrobenolt** [comment]
> if I'm not mistaken the travis issue is not caused by this PR? Looks like a missing environment variable for danger.

This is correct. :( We haven't spent the time to get Danger to run correctly on external contributions yet. But it seems that everything else is good.

We probably won't look at this today, but we should be able to look at it soon.

**Comment by sambauers** [comment]
Looks like this is what #46, #136, #138 are asking for.

**Comment by itsachen** [comment]
Any update on this PR? This feature would reduce the noise of our slack channels greatly since we'd be able to send alerts to different channels depending on environment, etc.

**Comment by noamt** [comment]
Is there any progress on this?
I really need this feature and would gladly contribute any work to move this forward

**Comment by berfarah** [comment]
@mattrobenolt I'm happy to take this work and bring it to the finish line. Apart from removing dangling commas, is there anything else that should be changed?

**Comment by Sean-Der** [comment]
@mattrobenolt If I fixed the merge conflict and comma issue would you be willing to merge this?

**Comment by samirageb** [comment]
@mattrobenolt You have multiple offers to push this across the finish line. Response?

**Comment by keithhalterman** [comment]
We really need this feature too, though it seems like we've lost the owner for this. 
@dcramer @macqueen you're pretty active in this project, anyway we can move this pr forward?

**Comment by dcramer** [comment]
@keithhalterman an updated slack integration is on the sentry roadmap, and will likely be released sometime shortly after the start of the year

at this point I'm going to close this out, as it adds a bunch of features that we may or may not want in the new integration, but either way we don't want to support them in the legacy integration

**Comment by mtsmfm** [comment]
@dcramer Any update?

**Comment by dcramer** [comment]
I wont be posting updates here, but the changes are already in Sentry master. They'll be made available to the general public as part of sentry.io in the near future.

**Comment by MaxBittker** [comment]
https://blog.sentry.io/2018/04/02/sentry-plus-slack @mtsmfm @keithhalterman 

this is live now!

**Pull request closed without merging**
