### PR TITLE
feat(victorops): Add issue and project id

### PR DESCRIPTION
**Pull request by Kaleb-Pace**
Added issue id as well as project id to victorops payload

Fixes https://github.com/getsentry/sentry-plugins/issues/252

### CODE REVIEW

**Comment by Kaleb-Pace** [comment]
Re-triggering Travis to see if build will pass. Last error seemed to be an out of memory exception causing webpack to fail.

**Comment by Kaleb-Pace** [comment]
@dcramer @markstory I hate to tag anyone like this, but I have noticed that some of the PRs as well as the issues go stale if not actively engaged. 

Is there anything I can do to help get this PR accepted and merged in? 

The build is simply failing due to an out of memory exception on the CI, but this builds locally.

**Comment by markstory** [comment]
@Kaleb-Pace If you rebase your changes the build should pass, as we've fixed the memory issues in master.

**Comment by kms254** [comment]
> @Kaleb-Pace If you rebase your changes the build should pass, as we've fixed the memory issues in master.

It looks like his last commit built and passed the checks. It is just pending review.

**Pull request merged**
