### PR TITLE
support for Github Enterprise 

### PR DESCRIPTION
**Pull request by QingsongYao**
support for Github Enterprise  by using environment variable GITHUB_BASE_DOMAIN and GITHUB_API_DOMAIN to set the git client.  Note, the above two variables are also used for Github Enterprise SSO, so it is safe to reused the two variables and assume people will set them if they use SSO.

### CODE REVIEW

**Comment by QingsongYao** [comment]
Any comments for this Pull request?

**Comment by rngtng** [comment]
What's status of this PR, would love to use this feature..

Anything to help bringing this to master?

**Comment by chulkilee** [comment]
I want this feature too.

Although I'm not a contributor of this project, but this PR should be updated for followings

* No merge commit; rebase it from master
* squash commits into one
* use plugin configuration, not os ENV, for configuration

**Comment by mandeepbal** [comment]
I also need this feature. I'm using the [sentry-auth-github](https://github.com/getsentry/sentry-auth-github) plugin right now but would love to just use the main sentry-plugins packages.

**Comment by QingsongYao** [comment]
Close this and open a new one at https://github.com/getsentry/sentry-plugins/pull/208

**Pull request closed without merging**
