### PR TITLE
Don't allow old and new plugins to coexist

### PR DESCRIPTION
**Pull request by mattrobenolt**
/cc @mitsuhiko @tkaemming @macqueen

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Not sure. Might make sense but also i'm not sure if people clean up their metadata always.

**Comment by mitsuhiko** [comment]
Thinking about this a bit more we might just use importlib for this:

```python
import importlib

def package_exists(name):
    return importlib.find_loader(name) is not None
```

**Comment by mitsuhiko** [comment]
And then use the actual import name and not the pypi name.

**Comment by mattrobenolt** [comment]
@mitsuhiko That only works on python 3.3+, so I'm sticking with `pkg_resources`.

**Pull request merged**
